In [6]:
# 多元回归分析举例
# 一家快递公司送货：X1： 运输里程 X2： 运输次数   Y：总运输时间

from numpy import genfromtxt
import numpy as np
from sklearn import datasets, linear_model

dataPath = r"Delivery.csv"
deliveryData = genfromtxt(dataPath, delimiter=',')

print("data")
print(deliveryData)

X = deliveryData[:, :-1]
Y = deliveryData[:, -1]

print("X:")
print(X)
print("Y:")
print(Y)

regr = linear_model.LinearRegression()

regr.fit(X, Y)

print("coefficients")
print(regr.coef_)
print("intercept: ")
print(regr.intercept_)

xPred = [[102, 6]]
yPred = regr.predict(xPred)
print("predicted y: ")
print(yPred)

data
[[100.    4.    9.3]
 [ 50.    3.    4.8]
 [100.    4.    8.9]
 [100.    2.    6.5]
 [ 50.    2.    4.2]
 [ 80.    2.    6.2]
 [ 75.    3.    7.4]
 [ 65.    4.    6. ]
 [ 90.    3.    7.6]
 [ 90.    2.    6.1]]
X:
[[100.   4.]
 [ 50.   3.]
 [100.   4.]
 [100.   2.]
 [ 50.   2.]
 [ 80.   2.]
 [ 75.   3.]
 [ 65.   4.]
 [ 90.   3.]
 [ 90.   2.]]
Y:
[9.3 4.8 8.9 6.5 4.2 6.2 7.4 6.  7.6 6.1]
coefficients
[0.0611346  0.92342537]
intercept: 
-0.868701466781709
predicted y: 
[10.90757981]


In [8]:
# 多元回归分析举例,添加类别型数据
# 一家快递公司送货：X1： 运输里程  X2： 运输次数  0：小轿车 1：SUV 2：卡车  Y：总运输时间

from numpy import genfromtxt
import numpy as np
from sklearn import datasets, linear_model

dataPath = r"DeliveryDummy.csv"
deliveryData = genfromtxt(dataPath, delimiter=',')

print("data")
print(deliveryData)

X = deliveryData[:, :-1]
Y = deliveryData[:, -1]

print("X:")
print(X)
print("Y:")
print(Y)

regr = linear_model.LinearRegression()

regr.fit(X, Y)

print("coefficients")
print(regr.coef_)
print("intercept: ")
print(regr.intercept_)

xPred = [[102, 6, 0, 1, 0]]
yPred = regr.predict(xPred)
print("predicted y: ")
print(yPred)

data
[[100.    4.    0.    1.    0.    9.3]
 [ 50.    3.    1.    0.    0.    4.8]
 [100.    4.    0.    1.    0.    8.9]
 [100.    2.    0.    0.    1.    6.5]
 [ 50.    2.    0.    0.    1.    4.2]
 [ 80.    2.    0.    1.    0.    6.2]
 [ 75.    3.    0.    1.    0.    7.4]
 [ 65.    4.    1.    0.    0.    6. ]
 [ 90.    3.    1.    0.    0.    7.6]
 [100.    4.    0.    1.    0.    9.3]
 [ 60.    3.    1.    0.    0.    4.8]
 [100.    4.    0.    1.    0.    8.9]
 [100.    2.    0.    0.    1.    6.5]]
X:
[[100.   4.   0.   1.   0.]
 [ 50.   3.   1.   0.   0.]
 [100.   4.   0.   1.   0.]
 [100.   2.   0.   0.   1.]
 [ 50.   2.   0.   0.   1.]
 [ 80.   2.   0.   1.   0.]
 [ 75.   3.   0.   1.   0.]
 [ 65.   4.   1.   0.   0.]
 [ 90.   3.   1.   0.   0.]
 [100.   4.   0.   1.   0.]
 [ 60.   3.   1.   0.   0.]
 [100.   4.   0.   1.   0.]
 [100.   2.   0.   0.   1.]]
Y:
[9.3 4.8 8.9 6.5 4.2 6.2 7.4 6.  7.6 9.3 4.8 8.9 6.5]
coefficients
[ 0.05500521  0.73671414 -0.2732739   0.63199413 